### PR TITLE
Update aerolib.csv

### PR DESCRIPTION
**Pull request by SocraticBliss**

### CODE REVIEW

**Comment by mailwl** [comment]
Can you find out names for NIDS from libkernel?
**b0cryxaTM4k  
2xg4JXvaJ6k**

**Comment by SocraticBliss** [comment]
> Can you find out names for NIDS from libkernel?
> **b0cryxaTM4k 2xg4JXvaJ6k**

If it was that easy we would have found them already :) we are bruteforcing these names (trial and error)

**Comment by mailwl** [comment]
ah, ok. if it help, first function just a call to `sysctlbyname("machdep.rcmgr_utoken_use_softwagner", &v2, &v1, 0LL, 0LL);`

**Comment by SocraticBliss** [comment]
Thanks for the tip, we are currently using all of the strings (in various files) and in various combinations, in order to try and crack it.... no luck yet though

**Comment by mailwl** [comment]
Understood. I am playing with running functions from ps4 libs on PC, this uses other libraries as well, and libkernel too lowlevel and have to be emulated. Unknown 2 functions is imported by other libs, and a don't remember if it really used in my purposed, but othr does. Thanks for your works!

**Pull request merged**
